production:
  sessions:
    default:
      hosts:
        - ds061391.mongolab.com:61391
      database: heroku_app35553281
      username: maha
      password: maha123456

development:
  sessions:
    default:
      database: maha_demo_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: maha_demo_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
